### ISSUE TITLE
Cant change presets after update

### ISSUE THREAD

**Issue by jevonsp** [antero111/plugin-presets#19]
Not sure what the problem is, but after the update I cant select any preset, the buttons to swap dont do anything/change color

**Comment by antero111** [comment]
Could you include some more info regarding preset loading e.g. a screenshot of your plugin panel.

**Comment by jevonsp** [comment]
![image](https://user-images.githubusercontent.com/8881225/182638053-96be4337-c1b2-4ae9-a41e-f4a1d84b2ac1.png)

I made a test preset and that one lights up, but clicking any of my old presets doesnt light them up. I can remake them again i guess.

**Comment by antero111** [comment]
How does one of those old presets look in the edit panel? Have you checked your runelite log for any errors?

**Comment by jevonsp** [comment]
![image](https://user-images.githubusercontent.com/8881225/182640810-ddd03d1e-9d7a-4fa7-b2f4-cd5f77bc1ad9.png) When I switch to a preset it appears to switch but still display that there are conflicted edits to plugins

This error:
```
[AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NullPointerException: null
	at com.evansloan.collectionlog.CollectionLogPlugin.lambda$onGameStateChanged$0(CollectionLogPlugin.java:244)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```
keeps showing up in the logs

**Comment by antero111** [comment]
> When I switch to a preset it appears to switch but still display that there are conflicted edits to plugins

Thats correct since there is conflicts between your current settings and the presets one. 

But it seems that some other hub plugin causes problems since after switching to a preset, it should not show any "modified" icons. In that picture apparently Menu entry swapper (extended?) fails to load.

After loading a preset, which plugins still show that icon?

**Comment by jevonsp** [comment]
![image](https://user-images.githubusercontent.com/8881225/182645758-9997a9b9-651b-4c71-9fa5-475d38d03772.png)

This one shows up for one of my presets, but even for ones with no modified plugins showing up it still doesnt turn "orange" on the switch saying I've switch to it

**Comment by antero111** [comment]
It has something to do with some hub plugin. With that Ba minigame plugin I was somewaht able to replicate the effect where the switch does not turn on but the settings get loaded except some plugin says its modified . After reinstalling that plugin, it seems not to appear anymore.

**Comment by MickWWW** [comment]
Am unable to select presets in the newest update. Reinstalling did not resolve the issue.

**Comment by antero111** [comment]
> Am unable to select presets in the newest update. Reinstalling did not resolve the issue.

Can you paste your preset data here, click the copy icon and paste it here. 

It's not working because of some hub plugin but no idea why

**Comment by antero111** [comment]
Afaik the preset loading works as intended but the switch does not turn on because the logic comparing your and the presets configurations fails because the old styled preset has settings that have changed and can't be compared. 

I tested with some presets from a friend and in his presets, party plugin caused the switch to fail since it failed to compare some configurations that have changed since creation of the old preset vs what the party plugin now has. 

When testing, even if the switch did not turn on, the plugin settings did get loaded right but only some of the party configurations caused it to fail.

**To fix your old presets,** open the edit panel and try to toggle the party switch. If that does not work, you could go trough the preset one by one and try to toggle the configurations. **Alternatively** see your old presets and create new presets to match those old ones and then delete the old presets that are not used.

**Comment by jevonsp** [comment]
I've decided to start fresh and make new presets, but I seem to not be understanding how the plugin even works now. 

I made a preset, and normal behavior was for the currently selected plugins/settings to be enabled. Does the "enable all current configs" button do that? 

furthermore, I dont even have the party plugin turned on and turning it on/off in 2 seperate presets fails to make it light up.

either way it appears to work at switching presets, its just the button. I'll have to get used to the new plugin ui

**Comment by jevonsp** [comment]
and also, it appears that volume level is not a selectable thing in the configs anymore (music, area, personal)

**Comment by antero111** [comment]
Volume sliders have been fixed [see here](https://github.com/antero111/plugin-presets/discussions/18#discussioncomment-3318439).

For the party plugin issue, it might be that there is other plugins e.g. some hub plugin like that were the configurations have changed and then the plugin fails to compare them.

Now when you make a preset, it's empty by default and then you add your configurations there you want to change. You can make presets like the old version by right clicking the + icon and selecting the "create with all configurations. 

New ui something new to learn and if you have something to change in it open a new discussion for it.

**Comment by antero111** [comment]
Switch not turning on when loading presets with invalid settings fixed [here](https://github.com/antero111/plugin-presets/commit/c89707008e7ae7abe79e905c54a37ef7b4bd4a52).

**Comment by jevonsp** [comment]
Thanks!
