### ISSUE TITLE
Toggle shows incorrectly for GPU plugin presets if GPU (Experimental) is installed

### ISSUE THREAD

**Issue by Jademalo** [antero111/plugin-presets#24]
This is a bit of a weird one.

If I have the "Plugin on/off" key selected for GPU and the plugin enabled, the toggle switch on the menu for that preset will break and always show as disabled. 
This seems to be some weird conflict with the GPU (Experimental) plugin, but I've no idea why. If that is installed, that key is saved in the plugin preset, and GPU is enabled, the toggle will show incorrectly.

**Comment by antero111** [comment]
Apparently the preset loading fails because both of those gpu plugins have the same configName. It seems that RuneLite does not care if there is plugins with same configNames...

**Comment by antero111** [comment]
Also the legacy gpu plugin causes this problem.

**Comment by antero111** [comment]
Fixed [here](https://github.com/antero111/plugin-presets/commit/c944e918c7bbe8e129eecc42ccf105786768d60f). The preset comparing failed because all of those gpu plugins have same configName (and also same setting configs). 

I don't know if its a RL feature or a bug but when you edit any of those GPU plugin configurations, the other 2 gpu plugins will also get updated with that setting. Nothing seems to be broken but it kinda messes up preset editing if using those certain gpu plugins.
