### ISSUE TITLE
Refresh presets

### ISSUE THREAD

**Issue by BladeBTW** [antero111/plugin-presets#32]
Hello!

Big fan of this plugin :)

Right now when I am playing multiple accounts I use the presets plugin to set various settings per account. Whenever I make a tweak I need to manuall reset the settings, would it be possible to add an option to the config where I can automatically let the settings refresh on an interval. 

Or the ability set up an hotkey with which you can refresh the plugin presets settings.

**Comment by antero111** [comment]
> Whenever I make a tweak I need to manuall reset the settings

What do you mean by this? Like clicking the refresh all button?

**Comment by BladeBTW** [comment]
![image](https://user-images.githubusercontent.com/52164618/190904574-cb83f3a9-6316-4ae0-bb3e-5fdd04858ec5.png)
An option to automatically Refresh Presets (maybe in config)
This would make alting so easy since I can set a preset on 1 acc then press a hotkey on all other accs to apply it.

I hope my chaotic explanation makes sense lol.

**Comment by BladeBTW** [comment]
I use multiple accounts for the same thing. So when i change a setting of one acount it has to be changed for all of them. If it would update automaticly i only have to change the setting of one account and the rest of the accounts would be getting the same settings.

**Comment by antero111** [comment]
Automatically refreshing presets (from the preset folder) would be possible by watching file changes in the preset folder. 

If you changed some preset, it would refresh on the other clients also but it would not change any configurations on those other clients. Those other clients need to load the changed preset again to use those changed configurations.

Maybe there could be some way to automatically load the changed configs so that you could "control" multiple client configs from one client.

Some auto update feature was considered here https://github.com/antero111/plugin-presets/issues/30, maybe this could add in to this?

**Comment by antero111** [comment]
Can you describe some "real world example" about how you would use this refresh feature?

**Comment by BladeBTW** [comment]
I daily play more than 1 account, usually more than 10.
And very often I change my setup for my accounts (each account uses their own .properties file). So for any change I want to make to my setup I usually have to go through each client and set the settings manually.

Method 1:
I use the presets plugin, set the settings I wanna change, bind it to a key. Reboot all my clients and press the key I set to change the settings. Then close down all the clients, remove the keybind (so I don't accidentally change anything ever again) and then reboot the clients.

Method 2:
Or alternatively as I learned today, go to the presets plugin folder and press refresh on each account, then use the keybind. Then Remove the keybind on 1 client and refresh on all accounts again.

The method that'd be epic in my opinion:
This whole process could be sped up alot if you could make the presets plugin check for refreshes on a set interval or as you mentioned above on a file change.

**Comment by antero111** [comment]
I'll test if it would be feasible to make it so that the client would auto refresh presets, Afaik it would help in your situation.

**Comment by BladeBTW** [comment]
> I'll test if it would be feasible to make it so that the client would auto refresh presets, Afaik it would help in your situation.

That'd be so amazing. 😊🙏

**Comment by antero111** [comment]
![NVIDIA_Share_Jz8P8LSeWM](https://user-images.githubusercontent.com/60603897/191576065-5b3edfd3-27e5-49aa-a5e4-d31c9d1990bc.gif)

Still needs some refining but the plugin now detects changes in the preset directory so now you would not have to click the refresh button ever again. Might remove the refresh button now since its basically useless. Only problem with this is that if the directory watcher that audits for the preset file changes fails, the plugin fails with it.

If presets are saved to config and clients are using different settings.properties files, those presets would not be added to others clients but those that are in the preset directory saved as 'local' would auto update across all open clients. 

Now making plugin config changes to multiple clients would be simple as changing the preset in one client and then loading that preset in the other clients.

**Comment by BladeBTW** [comment]
This is huge!!
Hope it gets approved.

**Comment by antero111** [comment]
This was added here: https://github.com/antero111/plugin-presets/commit/dfd316ca8fcea89d9c1c50653d90b6dc54f0b537. It will be available in the next plugin presets update.
