### ISSUE TITLE
Unintended behaviour with custom settings

### ISSUE THREAD

**Issue by antero111** [antero111/plugin-presets#34]
- Custom settings don't work as reliably than other settings.
- Plugin with custom settings turns off when preset is loaded.
- Custom settings in other presets reset when creating new ones.

See https://github.com/antero111/plugin-presets/issues/29 and https://github.com/antero111/plugin-presets/issues/28.

**Comment by buncieboy** [comment]
On the comment about them not working as reliably I noticed a strange bug with the screen markers. It appears the first preset with screen markers custom setting gets reset each time the client resets. For example I had crafting and herblore, but crafting kept being reset to having 0 markers only after the client restarted, would work fine otherwise. Deleting and recreating presets, markers etc did nothing, renaming crafting to ZZZ caused the herblore one to be reset instead. Creating a new preset with the name "A" and including screen markers on it prevented it resetting either crafting or herblore. Not sure if this falls under a new bug or if you want this under a new bug as I know custom settings are less supported?

**Comment by antero111** [comment]
Thanks for the comment. What you have described here fits under this issue. There is something wrong with how the custom settings are handled and I am not sure if that resettings happens because of some RuneLites internal logic that is being used wrong. I have noted that resetting also but never got to debugging it since doesn't hapen all the time.

**Comment by antero111** [comment]
Sould be fixed here https://github.com/antero111/plugin-presets/commit/56e5eae39a1ae3f4d15ac7cb6d54d91d0c7d85f6. Issue was that adding custom settings modified your current configurations and caused the presets "reset".
