### ISSUE TITLE
Region ID trigger for Plugin Presets

### ISSUE THREAD

**Issue by robuuuste** [antero111/plugin-presets#35]
Hi, do you think it would be possible to make presets trigger by Region IDs instead of a hotkey? I think it would be awesome if some presets could trigger automatically based on where you are. The way I see it, you could have a "base" preset which would be always on in every region unless overridden by another preset when entering their specific region(s). 
The only issue I see with this is that you can't really find Region IDs using RuneLite unless you are using developer tools. So you would probably have to add an option to show Region IDs. There are some 3rd party websites like ... where you could find them but it's not ideal.

**Comment by antero111** [comment]
It would be cool to bind presets to locations but since there is no real way for the normal player to know their region ID (or location as a whole) so I don't think its really viable.

Also that site is used for botting so let's not tell our plugin users to use that. 

Region ID:s are for developers and there should be some better way to define regions e.g. drawing to world map but thats something for _Plugin Presets++_ but currently I don't have the time to develop something like that.

**Comment by robuuuste** [comment]
Ah I completely understand and yes it would be very nice if regions could be drawn on the world map! 😄
