### ISSUE TITLE
Options to ignore certain plugins?

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [antero111/plugin-presets#4]
Would it be possible to add options to ignore the settings from certain plugins when updating a preset? Also on top of this could you add an option to ignore the voulme sliders when updating a plugin preset?

**Comment by septicsalmon** [comment]
as its difficult to sync common settings between presets, for example, adding items to the hidden/highlighted ground items list. If hold alt to add or remove and item from these lists it causes the current plugin to have "changes", i see no easy way to reflect these changes in a different preset without going into it and readding each item i come across.

as for the volume sliders it gets kind of annoying when i decide to turn up the music or turn off the sound effects and the plugin presets says i have a change that isnt in this preset and i have to consider if ive changed something elsewhere

**Comment by antero111** [comment]
Really good point. I'll look into how this could be implemented.

Possibly something similiar like the ground items plugins ignore items input box in the settings.

The notificator for unsaved plugin settings needs to be improved. Been thinking on some kind of pop-up ui that displayed all the unsaved configurations. Maybe that ui could have some kind of "ignore this configuration" for ease of use.

**Comment by septicsalmon** [comment]
Hovering over the little pencil that updates the preset to bring up a list of whats differen(or something similar)t would also be a great change

**Comment by Jademalo** [comment]
I figure it's probably best to reply to this ticket, since my idea is for the same problem but with a slightly different implementation. The biggest issue I see with the proposal of making it work like ground items with an ignore list is that you need to go in and manually override everything that you commonly change. I think a better approach would be the opposite.

My idea is best summed up as Partial Plugin Presets.
Essentially have two different types of preset. One is a complete plugin preset that replaces the full state of all plugins and settings within runelite, which works as the addon does currently. The other is a partial override that sits on top of the base settings state (either a preset or just the normal runelite settings) and overrides only a specific set of setting keys.

In terms of creating them, I'm envisioning something like this;
First you click to create your partial preset. This saves a temporary snapshot of the current plugin configuration, and instructs the player to change the settings they want to be overriden. Then, the player goes in and changes only the options they want to be changed in the override. The player then goes back to the plugin preset panel, and confirms. The difference between the initial state and the final state is compared, and only keys that have been changed are saved to the override.
When the override is enabled, only the keys that are in the override are changed, meaning the majority of settings are never touched.

An easy example of the use case for this is during a league - A "League" override that specifically changes Bank, Ground Items, and Item Prices to show high alch value instead of Grand Exchange value.
You could also have, say, a "Slayer" override that specifically enables things useful for slayer, such as aggro ranges, or a "bankstanding" override that changes various settings in GPU to lower fidelity.

Since I'm rarely wanting to change more than a couple of settings for any given preset, it makes sense to me to have the presets only save those changed settings rather than replacing every single setting.

I feel like this implementation will have a huge amount of flexibility, and also entirely solves the ground item list as described in the third post. Since the vast majority of settings wouldn't be touched by the partial preset, changing things such as adding highlights to ground items, tile markers, or NPC highlights wouldn't require every similar preset to be updated with those same changes.

**Comment by antero111** [comment]
Hi, haven't really had the time to do any development in this case.

I got in to that point that I had the ability to manually add plugins to ignores like we had planned here. While doing that I found out the exact problem that you had described here, it worked but it wasnt as flexible or usable one would want. Also ran into some technical difficulties and figured out we need change certain things before implementing this. 

@Jademalo Your idea is exactly what I had visioned after thinking some other alternatives to this plugin ignoring problem. I visioned it like some kind of "record" button that you enable in a preset to edit its. 

Probably will need to rewrite the plugin first before this will be implemented. I'll open an issue for v2.0 features.

**Comment by antero111** [comment]
See https://github.com/antero111/plugin-presets/discussions/6 for v2.0

**Comment by antero111** [comment]
New version of the plugin includes a new way of using presets and a new preset editing panel.  Now the idea is pretty much the opposite of how the plugin used to work, presets only should include those changes you wish to change between presets. 

So in this case ignoring e.g. music plugin happens by not including it to any preset. Making changes to the plugin then does not cause any modifications in other plugins. 

See the new readme and changelog for summary of new changes and features.
