### ISSUE TITLE
Unable to disable/enable presets

### ISSUE THREAD

**Issue by slyyyyyy** [antero111/plugin-presets#52]
I'm able to create a new preset template and adjust everything, but the slider/hotkey refuse to actually enable/disable plugins. I've tried using it with plugins that are shown to work in the general features examples, using only the slider without a hotkey yet assigned, storing them via cloud rather than local, and focus/unfocused. I am able to see the preset stored locally and the settings within the json. None have had any effect. When the preset is added and set at the default on position, it also does not change the state of a plugin that was already set to as off.

**Comment by antero111** [comment]
Iirc you are wondering that it should disable/enable the plugins you have included in the preset when turning the switch off/on. 

Clicking the orange switch does nothing at the moment. It's intentional because you need to have presets that have different configurations to same plugin and then you can switch between the presets to change the plugins state. 

So I believe in your case you have made presets and included some plugins to them but you don't have any changes in you plugin configurations to see the presets enable/disable switch to change. 

When you click the orange icon, it copies the presets plugin configurations to your current configurations and when the preset contains same configurations that you have currently on, loading the preset does nothing.

**Comment by slyyyyyy** [comment]
> Iirc you are wondering that it should disable/enable the plugins you have included in the preset when turning the switch off/on.
> 
> Clicking the orange switch does nothing at the moment. It's intentional because you need to have presets that have different configurations to same plugin and then you can switch between the presets to change the plugins state.
> 
> So I believe in your case you have made presets and included some plugins to them but you don't have any changes in you plugin configurations to see the presets enable/disable switch to change.
> 
> When you click the orange icon, it copies the presets plugin configurations to your current configurations and when the preset contains same configurations that you have currently on, loading the preset does nothing.

Great analysis. You are correct, I'm an idiot and was attempting to use it as a toggle rather than different states of the plugin. Thanks!

**Comment by antero111** [comment]
Actually I have been thinking of it being a toggle also (maybe with a setting to make a preset work as "toggler"). That way you could make a preset and then include some plugins to it and then when you load the preset it loads the configs from the preset and when you "disable" the preset, it would toggle every included on/off accordingly.
