### ISSUE TITLE
Plugin Presets Via Toggle

### ISSUE THREAD

**Issue by Puzzle-Drops** [antero111/plugin-presets#60]
![image](https://user-images.githubusercontent.com/86485071/234151713-f2f2f5d2-26e8-4333-81d5-7483e8cb0333.png)

I have two presets (4t and 7t) that I want to easily toggle back and forth. I could set one hotkey to b and the other to n, but it would be nice to develop the muscle memory to having it be the same hotkey. Have the plugin check for multiple hotkeys being the same. And have them cycle through the list of those presets when pressed. So I have 4t on. I press 'B', and 7t enables. I press 'B' again, and 4t comes back on. Etc. Thanks!

**Comment by antero111** [comment]
I guess it could be made to work like that. Currently the logic for the keybind/preset matching just loops the plugin preset list and enabled the first matching preset and it could be extended to enable the _next_ matching preset if there is multile presets with same keybind...

I'd say that this has some possibility to cause some usage problems when some presets have the same keybind. Someone might think that 2 presets having the same keybind turns both presets on with that single keybind; which it doesn't do and will not do because of presets possibly collapsing together. That same problem applies to the preset keybind cycling. 

Should same keybinds notice somehow that it cycles to the next one? If so, then how?

**Comment by antero111** [comment]
Closing as stale

**Comment by antero111** [comment]
Reopening this after there was other requests for this kind of feature. Will be implemented as so when 2 presets have same keybinds they toggle between each other and for multiple presets withg same keybind the next presets in the preset list will be enabled.

**Comment by antero111** [comment]
Added in ae1b28ec9000bc7ec17916b5f2512cf662e63494.
2 presets with the same keybind toggle between them and 3 or more cycle from top to bottom in the preset list.
![wMla1zZT26](https://github.com/antero111/plugin-presets/assets/60603897/cabb083a-d99e-41a3-8450-ee81f290db7d)
