### ISSUE TITLE
This plugin clearly induces occasional stuttering

### ISSUE THREAD

**Issue by Hieb** [antero111/plugin-presets#67]
I only now had the idea to report this issue, but on my end having the plugin enabled in Runelite results in occasional stuttering and clear loss of performance. 
Many times I will be doing something that requires fast accurate clicking and wonder why i just yellow clicked on a massive click box, why the camera stuttered or why my action didnt process, and remember that I had the plugin open. You should look into how many resources it takes up and how frequently to try and resolve this. 
My workaround currently is to keep the plugin deactivated, then activate it and change what i need to change, then turn it back of, which I wholeheartedly reccommend to anyone with a similar issue.

It's definitely not a PC issue since my specs are quite good. But the performance spikes undeniably stem from this one plugin and are severe.

**Comment by antero111** [comment]
The plugin does not really use any more resources than any other plugin you might have one. Once you change your RuneLite configurations somehow, the plugin reacts to that and updates its state accordingly. 

Most likely the issues is in your installed Plugin Hub plugins. Some of those might update RL configs too often but that its not my concern. Try to test you disabling all of your Plugin Hub plugins and see if the issue still persists. If the stuttering persists then we can start looking into this.

It has been a while since the last update and RuneLite has had many updates since then so it might be possible that the core client does some configuration updating that I have not taken into consideration before.
