### ISSUE TITLE
Allow applying changes to all presets

### ISSUE THREAD

**Issue by jfabellera** [antero111/plugin-presets#7]
Right now, if I change something that I want to be reflected in all of my presets, I have to select the preset, make the change, save, and repeat.

Would be nice to apply changes to all.

**Comment by antero111** [comment]
Hi, the plugin is in the middle of a rework and the new version will include a new way for editing presets.
![kuva](https://user-images.githubusercontent.com/60603897/167250652-6fb452ed-947b-4dda-a770-3eadf791f813.png)
![kuva](https://user-images.githubusercontent.com/60603897/167250657-d8455db3-9ac4-4790-9afb-28edfb656b83.png)

If you made changes to some plugin, presets will notify about the change in the edit view as "Modified" and you can update the configuration in the edited preset if wanted. 

In your case, this edit button could have some sort of "apply to all presets" context menu option for situations when the change should apply presets.

I will look into this if its feasible and if so, it will come out once the rework is finnished. See [plugin-rewrite](https://github.com/antero111/plugin-presets/tree/plugin-rewrite) branch.
 Thanks for the suggestions!

**Comment by antero111** [comment]
In the upcoming version, presets are no more copies of _all_ your configurations but more so only presets of the plugins that should change when enabling presets. So if you wanted to use same settings for a plugin in every preset, you simply take the plugins configurations off the presets so that it does not get changed. Examples of not saving plugin configurations to presets would be with music or ground items.

In addition to this you can now add and remove plugin configurations from all presets on one go by right clicking the switch.
![kuva](https://user-images.githubusercontent.com/60603897/167272053-20bb5036-1425-41f9-968a-4fd982534af7.png)

**Comment by jfabellera** [comment]
Awesome, thanks for the update. Looking forward to it!
